---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "paulsalden.com"
keywords:    "paul, salden, jekyll, singlepaged"
description: "my digital portfolio"
source_link: "https://github.com/PaulSalden/SinglePaged"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#000000'
  white:     '#ffffff'
  blue:      '#2196F3'
  green:     '#4CAF50'
  purple:    '#9C27B0'
  orange:    '#FF9800'
  turquoise: '#009688' # actually teal

navbar_color:    '#3F51B5'
